name: CI of yatt
    
on:
  push:
    branches:
     - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    #- run: npm run test --if-present
    - run: pwd    
    - run: ls

    - name: stop web-server
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: systemctl stop yattFE.service
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }}
        username: ${{ secrets.REMOTE_USER }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        privateKey: ${{ secrets.SSH_KEY}}

    - name: Copying files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        rm: false
        source: "build/"
        target: "${{ secrets.REMOTE_DIR }}"
        
    - name: start web-server
      uses: garygrossgarten/github-action-ssh@release
      with:
       command: systemctl start yattFE.service
       host: ${{ secrets.REMOTE_HOST }}
       port: ${{ secrets.REMOTE_PORT }}
       username: ${{ secrets.REMOTE_USER }}
       passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
       privateKey: ${{ secrets.SSH_KEY}}
